### ISSUE TITLE
Incorrect status displaying

### ISSUE THREAD

**Issue by brettmarquard** [HL7/hl7-c-cda-ex#17]
Cat hair is withdrawn in the readme.
It is displaying as pending here:
http://hl7-c-cda-examples.herokuapp.com/examples/1

**Comment by astechishin** [comment]
Brett,

When I look at the readme for Cat Hair in GitHub, it still shows as approved. https://github.com/HL7/C-CDA-Examples/tree/master/Allergies/Allergy%20to%20cat%20hair

Is this a pending commit?

**Comment by brettmarquard** [comment]
Nice, I resynch and now it says ‘withdrawn’ instead of pending!

**Comment by brettmarquard** [comment]
Now this says pending: http://hl7-c-cda-examples.herokuapp.com/examples/1

Readme says withdrawn



From: Brett Marquard
Sent: Thursday, November 03, 2016 11:59 AM
To: 'HL7/hl7-c-cda-ex' <reply@reply.github.com>; HL7/hl7-c-cda-ex <hl7-c-cda-ex@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [HL7/hl7-c-cda-ex] Incorrect status displaying (#17)

Nice, I resynch and now it says ‘withdrawn’ instead of pending!

**Comment by astechishin** [comment]
Added a line to the example details showing the last metadata update timestamp, this will help verify that the GitHub contents and the example site are in sync. 

As well, the automatic update process has not been rolled out to the production site. Updates to metadata will not appear without metadata reload.

**Comment by brettmarquard** [comment]
Did you sync? I don’t see it

**Comment by astechishin** [comment]
Not yet, when I sync, the issue will close again
