### ISSUE TITLE
Other supporting documentation

### ISSUE THREAD

**Issue by brettmarquard** [HL7/hl7-c-cda-ex#18]
What will happen to the example search tool if we load a readme with a reference to [Medication Frequency](https://docs.google.com/document/d/1Y0Z458o_MrR2aPnpx6EygO6hpI88Bl95esjRWZ0agtY/edit?usp=sharing)

**Comment by astechishin** [comment]
Brett,

Could you post an example or send me an example of what you are thinking of doing?

Note, not all people may have access to a Google doc but I believe a reference in the metadata text would be fine.

**Comment by brettmarquard** [comment]
Added one
https://github.com/HL7/C-CDA-Examples/tree/master/Medications/Medication%20Frequency%20Patterns

**Comment by astechishin** [comment]
Proposed alternate in a pull request on C-CDA-Examples
