### ISSUE TITLE
Link name is number rather than sample

### ISSUE THREAD

**Issue by brettmarquard** [HL7/hl7-c-cda-ex#20]
The links include a random '#' rather than the sample name in link. 

Could we update:
http://hl7-c-cda-examples.herokuapp.com/examples/4

To;
http://hl7-c-cda-examples.herokuapp.com/examples/Allergy to specific drug Codeine

**Comment by astechishin** [comment]
This is called 'slugging'

The numbers are the database Ids for each metadata record.  The current URL follows standard RESTful web application practices (as the underlying framework is a RESTful web framework). It is possible to add slugs to the application but this would require a non-trivial amount of work and may cause issues with the example authors.

For instance, in the example provided in the description, the URL actually stops at the word 'Allergy' and does not include 'to specific drug Codiene'. URLs do not include spaces. To change the above to a valid URL would mean either translating the spaces to either the '_' character or to URL encode the name. The URL-encoded version would look like: http://hl7-c-cda-examples.herokuapp.com/examples/Allergy&20;to&20;specific&20;drug&20;Codeine
Which in my opinion is not an improvement.

I would advise against proceeding with this item.

**Comment by brettmarquard** [comment]
planning a different method for permalink
