### ISSUE TITLE
Show / index all that are referenced by ONC 2015 certification

### ISSUE THREAD

**Issue by gecole** [HL7/hl7-c-cda-ex#21]
maybe this is additional metadata or some other implementation, but would be nice to be able to Filter and see all Certification referenced examples

**Comment by astechishin** [comment]
I believe this would require additional metadata

**Comment by brettmarquard** [comment]
This would require additional meta data, but that would be pretty easy to add. How would you want them flagged? Separate index file that lists all relevant, or update readme files that are relevant?

**Comment by gecole** [comment]
I think this is worthy of some Examples task force discussion, but I was thinking that I'd probably like to filter on the ONC Referenced examples, in a manner that one can filter by Active status, etc.

**Comment by astechishin** [comment]
Please update with any discussion from the Examples Task Force.

This item would require updates to each and every Readme files to indicate certification. Additionally, the metadata parsing, the metadata records in the database, the search entry screens, the query builder and the example detail display would all require updating.

**Comment by brettmarquard** [comment]
Will put on next agenda, two team members brought this request forward

**Comment by brettmarquard** [comment]
Example Task Force suggested adding 'certification' to the keywords and comments -- will test with a few.

**Comment by astechishin** [comment]
Adding text to an existing section is far more difficult to implement rather than adding a new section. If we proceed on this item I would need to have a new section added to the README for each example that is certified. For example:

###Keywords

* substance, allergies, allergy

###Certification
*ONC

**Comment by brettmarquard** [comment]
would the keyword 'certification' be picked up in search?

**Comment by astechishin** [comment]
If you add it to the keywords, yes. You could use the keywords as a 'tag'. But all of your authors and all of the users will then need to know about this 'hidden' feature.

**Comment by brettmarquard** [comment]
What would you suggest as potential solution?

**Comment by astechishin** [comment]
Adding 'certification' to the keywords would indeed work and require no additional coding. However, it would be a secret to the average user. How would Jennifer Developer know that by entering the word certification, she will find the ONC certified examples? Even if there is an instruction added to help screens, at best only 20% of casual users would see it. 

If this feature is important for people beyond the borders of HL7, that is Jennifer Developer and her teammates, then we should make it explicit. That would mean adding an explicit attribute to the metadata and a filter on the search panel. If this feature is only to assist the team creating the examples, then add the keyword.

Hope this helps determine the best course for implementation.

**Comment by brettmarquard** [comment]
Filter on search panel makes a lot of sense to me.

What 'tagging' would you want in the readme files?

**Comment by astechishin** [comment]
* Will update metadata parsing to evaluate new tag ###Certification and look for the value ONC as a list item.
* Will add ONC Certification as a filter button
* Will add ONC Certification attribute to example metadata in database
* Will add Certification to search form class
* Will add certification to query builder
[20161215_Example_Search_Tool_Certification_Flag-AS-2.docx](https://github.com/HL7/hl7-c-cda-ex/files/661796/20161215_Example_Search_Tool_Certification_Flag-AS-2.docx)
