### ISSUE TITLE
Social History button is dancing

### ISSUE THREAD

**Issue by brettmarquard** [HL7/hl7-c-cda-ex#23]
Open tool in IE.

Select problem, procedures, or results -- Social history button moves all over!

**Comment by astechishin** [comment]
Unfortunately the description is terse and I cannot match against anything in the UI. There is no Social history button.

Perhaps if you could include a screen capture, it could make problem determination easier.

**Comment by astechishin** [comment]
[Issue23_Social History Button Dances.docx](https://github.com/HL7/hl7-c-cda-ex/files/584648/Issue23_Social.History.Button.Dances.docx)

**Comment by astechishin** [comment]
Will investigate CSS issue that causes button placement to shift when selecting other button in section filter on IE
