### ISSUE TITLE
search for: lab location and get 6 search results, but none about lab location

### ISSUE THREAD

**Issue by gecole** [HL7/hl7-c-cda-ex#24]
look at first search result returned: http://hl7-c-cda-examples.herokuapp.com/examples/18
on that page search for lab - found in the word available
the word location is found on the page

change the search to: "lab location" 
hoping to indicate that we want that phrase, not two distinct words, and still get the 6 search results

**Comment by astechishin** [comment]
The search is word and text-based, it is not a string based search (which is what would be necessary to find phrases). As such, it did not match on lab in available.

The advantage of the text-based search is if you enter 'location' it will match anything that has 'locations' (which a string search WILL NOT do). Currently if you enter the words 'lab' and 'location' it will return everything that has either word. This is far more better to support people who may not know exactly what they are searching for. 

There is an extended syntax that I have not described that would let you locate only the entries that have both lab and location (you need to enter lab&location exactly, no spaces with an ampersand between the words). When I executed the combined term search, I found no entries that had both of the words lab and location.

The reasoning behind returning more results is that uninitiated user will often not look for highly specific phrases but rather enter one or two terms to see what is returned and then refine their search or pick from the results. People who enter very specific things, usually already know what they are looking for. 

Another advantage of the text-based search is that it is possible to add weighting in a future release as well as trigrams.

Hoep this helps

**Comment by astechishin** [comment]
Closing issue will re-open if answer unsatisfactory
