### ISSUE TITLE
No sample displayed

### ISSUE THREAD

**Issue by brettmarquard** [HL7/hl7-c-cda-ex#28]
http://hl7-c-cda-examples.herokuapp.com/examples/10

**Comment by astechishin** [comment]
Sample file is named incorrectly. Must follow the format of: xxxxxx(C-CDA2.1).xml as agreed

**Comment by brettmarquard** [comment]
Do we have that in the tool documentation?

**Comment by astechishin** [comment]
Honestly, I wouldn't know. What did you put in the instructions for sample authors and maintainers of the GitHub repository? That wasn't part of the search tool and I expect would have been part of the examples repository piece.

Note: the (C-CDA2.1) was put into the files to allow for the differentiation of sample files when multiple versions are stored in the same repository directory. The requirement to support multiple releases in the same repository was added very early in the discussion.

**Comment by brettmarquard** [comment]
happy to add to readme on main page of samples repo -- are there other items I should add?

**Comment by astechishin** [comment]
I would think you would want to add the directions for directory structure, the expected files in each directory (such as the Readme.md), a description of what should be in the Readme.md files. All the things that you are thinking about when you create examples. You may also wish to mention that directory renames are a large problem for the automatic update and require a complete reload (which is not an overly complicated procedure but needs the search tool to come down for about 20 minutes) which needs to be triggered by an operator. Let me know when you have something posted and I will comment.
