### ISSUE TITLE
File rename results in samples appearing twice

### ISSUE THREAD

**Issue by brettmarquard** [HL7/hl7-c-cda-ex#29]
see: http://hl7-c-cda-examples.herokuapp.com/sections/2

**Comment by astechishin** [comment]
Yes, this was explained previously. Renaming the directories requires a complete reload of the sample metadata. There is no way to determine that the 'new' directory replaces another directory or to link the replaced and replacement directories. 

You need to be certain of the directory names prior to performing the push to GitHub.

Once you have completed all the directory renaming activities, send me a note and I will regenerate the metadata repository.
