### ISSUE TITLE
Directory update instructions

### ISSUE THREAD

**Issue by brettmarquard** [HL7/hl7-c-cda-ex#30]
Is it possible to add instructions after here on howto regenerate the folder structure:
"The unattended update will not detect restructuring of the C-CDA Example repository (directory renaming or deletion) or the removal of examples."

This area is showing duplicates (emailed previously):
http://hl7-c-cda-examples.herokuapp.com/sections/2

**Comment by astechishin** [comment]
Data regeneration and upload requires operator access to the Heroku application. The instructions for running the data generation are on the main readme of this repository.

At present, a request to regenerate the metadata can be sent to me directly (or by creating an issue here). Going forward, the EST work group will manage the regeneration requests (which likely means it will still be me).
