### ISSUE TITLE
Return to result list always takes to full

### ISSUE THREAD

**Issue by brettmarquard** [HL7/hl7-c-cda-ex#40]
Select Encounters
Select first example - "Hospital Discharge Encounter with Billable Diagnoses"
Select button 'return to result list'

I would have expected to return to 'Encounters' but instead it says query found 50 examples.

**Comment by astechishin** [comment]
The 'Return to Result List' takes the user to search listing not the section list. It has always worked this way.

You can navigate back to the Section List with the back button.

If this is confusing, there are two options:

1. Remove the 'Return to Result List' button
2. Add a new button 'Section List'

**Comment by brettmarquard** [comment]
Well, that doesn't work either!  ....try to search 'No known', select 'No Known Allergies', and then select 'Return to Result List'. 

It would be great to have it just return one screen

**Comment by astechishin** [comment]
Does that mean select option 1?

**Comment by astechishin** [comment]
I think I might be able to do something, will verify and post an update

**Comment by astechishin** [comment]
I can change the button to return to the previous screen. This does require Javascript magic, which means if Javascript is disabled, the button will not function.

Should I proceed with the change?

**Comment by jddamore** [comment]
Can you provide a link to the proposed code?

**Comment by astechishin** [comment]
<a href="javascript:history.back()" class="button small" >return to result list</a>
