### ISSUE TITLE
Permanent home for search

### ISSUE THREAD

**Issue by brettmarquard** [HL7/hl7-c-cda-ex#47]
Did HL7 determine a final home for the search tool?

**Comment by jddamore** [comment]
i.e. http://hl7-c-cda-examples.herokuapp.com/ ...is this app moving from herokuapp.com domain at some point?

**Comment by dhamill** [comment]
The permanent home is:
www.HL7.org > Resources > Tools & Resources > CDA Tools > C-CDA® Example Search Tool

**Comment by brettmarquard** [comment]
Did you consider moving to HL7.org?

**Comment by dhamill** [comment]
Brett,
What are your thoughts (and even the Examples Task Force's thoughts) on the following URL...
ccdaexamplesearch.hl7.org

Just want to be sure that it accurately depicts what we feel this tool will be in the future.

**Comment by brettmarquard** [comment]
Drop the extra c.

CDAexamplesearch…

**Comment by jddamore** [comment]
Can you even go shorter (easier to remember)?

cdasearch.hl7.org

**Comment by dhamill** [comment]
I'll ask our Webmaster to make it cdaexamples.hl7.org in case he hasn't done the work already.

**Comment by astechishin** [comment]
DJ created a DNS entry for http://cdasearch.hl7.org/ and has verified
