### ISSUE TITLE
Sample not appearing

### ISSUE THREAD

**Issue by brettmarquard** [HL7/hl7-c-cda-ex#48]
Some samples are not appearing.

For example: http://hl7-c-cda-examples.herokuapp.com/examples/21
C-CDA-Examples/Header/Patient Previous Name/Patient Previous Name(C-CDA R2.1).xml

**Comment by astechishin** [comment]
Example file not named correctly, see C-CDA-Examples/Allergies/Allergy to cat hair/Allergy to specific substance cat hair(C-CDA2.1).xml and not difference C-CDA2.1 vs. C-CDA R2.1
