### ISSUE TITLE
Add link on main search page to log issues

### ISSUE THREAD

**Issue by brettmarquard** [HL7/hl7-c-cda-ex#49]

**Comment by astechishin** [comment]
This sounds like a good idea but where should point to? If you think that we should use the issue log here, who will bear the responsibility of responding?

**Comment by brettmarquard** [comment]
Does EST have a policy?

Don't  you have a lifetime free contract :)

**Comment by astechishin** [comment]
Normally, in EST the responsibility falls to the Webmaster. I would need Dave to comment on this.

**Comment by dhamill** [comment]
One often does sign away a lifetime of free support when joining HL7 ;-)

I do believe issues should go to the HL7 Webmaster.  We can include this item in our EST discussion regarding moving the tool over to HL7's server/github repository.
